### PR TITLE
Makefile.msc modifications to make it possible to build on Windows

### PR DESCRIPTION
**Pull request by jlehtnie**

### CODE REVIEW

**Comment by brodybits** [comment]
What is the status of this one? I suspect it could help some others.

**Comment by developernotes** [comment]
Hi @brodybits 

We were in the middle of a software release when the contributor agreement was signed, we plan to include this in a follow up release.  Thanks!

**Comment by brodybits** [comment]
Thanks and thanks to your team for maintaining!

**Comment by justinclift** [comment]
Heh Heh Heh

Wish I'd noticed this PR before starting into writing up a doc on how to get it working:

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/wiki/Win64-setup-—-Compiling-SQLCipher#values-to-be-changed

(note, that's a temp fork location.  The real doc once ready with be in the github.co/sqlitebrowser/sqlitebrowser wiki)

Any idea of timeframe before someone gets back into this PR?

**Comment by developernotes** [comment]
Hi @jlehtnie 

I apologize for just getting back to you on this pull request. We [integrate](https://github.com/sqlcipher/sqlcipher#contributions) all pull requests from the [`prerelease`](https://github.com/sqlcipher/sqlcipher/tree/prerelease) branch. Unfortunately your changes do not apply cleanly to `prerelease`. Would you mind taking alook into the changes you require on the `prerelease` branch? Thanks!

**Comment by jlehtniemi-broadsoft** [comment]
Sorry about the delayed response. The PR has been rebased on prerelease. The good news is that the changes in the sqlite3 source make this patch even more trivial.

**Comment by justinclift** [comment]
@jlehtniemi-broadsoft With the nmake command in the commit message, should that info be added to the repo README.md (or maybe somewhere for developer documentation)?

**Comment by brodybits** [comment]
What is the status of this one?

**Comment by developernotes** [comment]
Hi @jlehtnie, @jlehtniemi-broadsoft, @brodybits,

We have just pushed a new [change](https://github.com/sqlcipher/sqlcipher/commit/1963d489e0fe3cb9a975652f1b2ca6ad4e274759) that will allow you to specify the additional linker arguments necessary on the command line. Something like the following:

```
nmake /f Makefile.msc ^
     USE_AMALGAMATION=1 NO_TCL=1 ^
     LTLINKOPTS="%openssl_dir%\lib\libeay32.lib" ^
     SQLITE3DLL=sqlcipher.dll SQLITE3EXE=sqlcipher.exe ^
     SQLITE3LIB=sqlcipher.lib ^
     OPT_FEATURE_FLAGS="-I %openssl_dir%\include -DSQLITE_HAS_CODEC=1 -DSQLCIPHER_CRYPTO_OPENSSL=1"
```

Please let us know if you have any additional questions or concerns. Thanks!

**Pull request closed without merging**
