### PR TITLE
fix building with libressl since v2.7.1

### PR DESCRIPTION
**Pull request by whuji**
Changes proposed in this pull request:
-

### CODE REVIEW

**Comment by sjlombardo** [comment]
We will be making changes to address this issue in the next SQLCipher release.

**Comment by sjlombardo** [comment]
We will be making changes to address this issue in the next SQLCipher release.

**Comment by whuji** [comment]
Ok, I will use my own repo in the meantime.

**Comment by sjlombardo** [comment]
We didn't merge this pull request, but the underlying issue should now be resolved in the SQLCipher 4 release. It should now be possible to build against LibreSSL 2.7.0+ (and also OpenSSL 1.1.x).

**Pull request closed without merging**
