### PR TITLE
NSS crypto implementation

### PR DESCRIPTION
**Pull request by eoger**
Changes proposed in this pull request:
- Add a [NSS](https://nss-crypto.org/) crypto implementation for SQLCipher.

`./testfixture test/sqlcipher.test` passes without any issues on my computer.
You might have to pass `-I/usr/include/nspr` to the `configure` script.

### CODE REVIEW

**Comment by sjlombardo** [comment]
Hello @eoger thank you so much for proposing this contribution. We use a CLA based on the [Harmony FOSS templates](http://harmonyagreements.org) for the SQLCipher project. Could you please take a quick look at the [contributor agreements](https://www.zetetic.net/contributions/), and then let us know at [support@zetetic.net](mailto:support@zetetic.net) which would be appropriate (i.e. individual or organization)? Once we have a CLA in place we can review the proposed pull request. Thanks!

**Comment by eoger** [comment]
I believe our legal team sent you the signed papers today, thanks!

**Comment by sjlombardo** [comment]
@eoger thank you, we did receive the agreement and we’ll be taking a detailed look at this pull request shortly

**Comment by eoger** [comment]
@sjlombardo any update on the review?

**Comment by sjlombardo** [comment]
Hello @eoger - initial code review of the branch looks good. We're working on testing now locally.

**Comment by sjlombardo** [comment]
Hi @eoger we tested this and merged it into the prerelease branch today. We will merge it into master and include it along with the next official release of SQLCipher.

**Comment by eoger** [comment]
That's great, glad to see my patch merged, thanks a lot!

**Pull request merged**
