### PR TITLE
mbedcrypto implementation

### PR DESCRIPTION
**Pull request by jc-lab**
Changes proposed in this pull request:
- Add a mbedcrypto implementation for SQLCipher.

### CODE REVIEW

**Comment by sjlombardo** [comment]
Hello @jc-lab  thank you so much for proposing this contribution. We use a CLA based on the [Harmony FOSS templates](http://harmonyagreements.org) for the SQLCipher project. Could you please take a quick look at the [contributor agreements](https://www.zetetic.net/contributions/), and then let us know at [support@zetetic.net](mailto:support@zetetic.net) which would be appropriate (i.e. individual or organization)? Once we have a CLA in place we can review the proposed pull request. Thanks!

**Comment by jc-lab** [comment]
Hello @sjlombardo.
Thank you for kind description.
I signed a CLA contract. Please review it. Thanks.

**Comment by jclab-joseph** [comment]
It is me. my account is changed.

**Comment by sjlombardo** [comment]
Hello @jclab-joseph - Thank you for submitting this PR. While we appreciate this proposed contribution, we have decided not to merge this new crypto provider implementation into the core SQLCipher codebase at this time.

As interest in SQLCipher has grown we've seen an increasing number of requests for new cryptographic provider integrations. We consider providers that are included in SQLCipher core to be supported by our team. As part of the official product, we need to:

 1. thoroughly review and understand the incorporated code
 2. perform testing during new releases
 3. maintain awareness of ongoing changes to the upstream cryptographic module
 4. ensure consistency and compatibility of licensing
 5. provide an equivalent level of support to the community as we do with other modules

Adding new providers also tends to fragment the install base of SQLCipher. In our experience this can lead to other related complications like environmental / build issues, troubleshooting problems, incompatibilities, performance variations, etc. 

As a result, merging this new provider would entail substantial effort and a long-term commitment that we are not prepared to make at this time.
 
That said, you are still able to use this cryptographic module with SQLCipher yourself. We built the SQLCipher provider interface so that developers could substitute modules of their choice to meet specific requirements. You can continue to maintain your own sources (e.g. in a separate GitHub repository) and providing ongoing support on behalf of yourself and any other developers that you choose to share your code with. 

It is difficult to make this kind of decision because we don't want to discourage open discussion and contribution. Still, we feel strongly that it is in the best interest of the SQLCipher project. 

As a final note, we are not singling out this PR specifically. Rather we are making this decision across several open pull requests simultaneously and cross posting this message accordingly. I hope you understand, and thank you again for your time.

**Pull request closed without merging**
